#ifndef __MODULE_BOARD_CONFIG_H
#define __MODULE_BOARD_CONFIG_H



#define AT_SLEEP_CTRL_PIN P14
#define AT_MODE_CTRL_PIN P15
#define AT_SLEEP_PIN P20
#define AT_CONNECT_PIN P23
#define LOG_PIN  P25


#endif