mtb_version: 4
chip: ch6121        # cb2201 / cb6501 / sc5654a
diff:
  digest_type: SHA1
  signature_type: RSA1024
  fota_version: 0
  ram_buf: 50      #DEC     KB   ( max ram need)
  flash_buf: 16     #DEC    KB   ( buffer size)
  flash_sector: 4096 #DEC   byte ( flash sector)
  diff_mode: 010    #BIN
  double_control: 1
flash:
  base_address: 0x11000000
  run_base_address: 0x1FFF3800 # base address of Storage
  sector: 4096       # Bytes
  size: 524288      # $(sector count) * sector
partitions:
  - { name: bomtb,  address: 0x11002100, size: 0x001000 }
  - { name: imtb,   address: 0x11005000, size: 0x002000 }
  - { name: FCDS,   address: 0x11004000, size: 0x001000 }
  - { name: boot,   address: 0x11009000, size: 0x008000, load_addr: 0x1fff4800}
  - { name: jumptb, address: 0x11011000, size: 0x001000, load_addr: 0x1FFF0800, update: FULL, verify: true }
  - { name: prim,   address: 0x11012000, size: 0x016800, load_addr: 0x20000000, update: FULL, verify: true }
  - { name: xprim,  address: 0x11032000, size: 0x018000, update: FULL, verify: true }
  - { name: misc,   address: 0x1104A000, size: 0x033000 }
  - { name: kv,     address: 0x1107D000, size: 0x3000, update: FULL, verify: false }