#ifndef _PIN_H_
#define _PIN_H_

#include <gpio.h>

#define EXAMPLE_ADC_CHANNEL_USR_DEF0         4
#define EXAMPLE_ADC_CH_PIN_USR_DEF0          EXAMPLE_ADC_CH4
#define EXAMPLE_ADC_CH_PIN_USR_DEF0_FUNC     EXAMPLE_ADC_CH4_FUNC
#define EXAMPLE_ADC_CHANNEL_DEF1             7
#define EXAMPLE_ADC_CH_PIN_USR_DEF1          EXAMPLE_ADC_CH7
#define EXAMPLE_ADC_CH_PIN_USR_DEF1_FUNC     EXAMPLE_ADC_CH7_FUNC
#define EXAMPLE_ADC_CHANNEL_DEF2             6
#define EXAMPLE_ADC_CH_PIN_USR_DEF2          EXAMPLE_ADC_CH6
#define EXAMPLE_ADC_CH_PIN_USR_DEF2_FUNC     EXAMPLE_ADC_CH6_FUNC

#define EXAMPLE_ADC_CH4     GPIO_P14
#define EXAMPLE_ADC_CH4_FUNC    ADCC
#define EXAMPLE_ADC_CH7     GPIO_P15
#define EXAMPLE_ADC_CH7_FUNC    ADCC
#define EXAMPLE_ADC_CH6     GPIO_P20
#define EXAMPLE_ADC_CH6_FUNC    ADCC

#endif 