mtb_version: 1
chip: cb2201        # cb2201 / cb6501 / sc5654a
diff:
  digest_type: SHA1
  signature_type: RSA1024
  fota_version: 0
  ram_buf: 50      #DEC     KB   ( max ram need)
  flash_buf: 4     #DEC     KB   ( buffer size)
  flash_sector: 512 #DEC     byte ( flash sector)
  diff_mode: 010    #BIN
flash:
  base_address: 0x10000000
  run_base_address: 0x10000000 # base address of Storage
  sector: 512       # Bytes
  size: 262144      # $(sector count) * sector
partitions:
  - { name: imtb,    address: 0x10000000, size: 0x001000 }
  - { name: tee,     address: 0x10001000, size: 0x006000, update: DIFF, verify: true }
  - { name: boot,    address: 0x10007000, size: 0x006000 }
  - { name: prim,    address: 0x1000D000, size: 0x030A00, update: DIFF, verify: true }
  - { name: misc,    address: 0x1003DA00, size: 0x001000 }
  - { name: kv,      address: 0x1003EA00, size: 0x000C00 }
  - { name: lpm,     address: 0x1003F600, size: 0x000200 }
  - { name: otp,     address: 0x4003F800, size: 0x000800 }
